export const fruits = ["pomegranate", "peach", "pear", "orange", "sour cherry"];
export const randomText = [
    "suggest",
    "bag",
    "ponder",
    "zinc",
    "come",
    "slip",
    "coherent",
    "infamous",
    "expect",
    "unsightly",
    "mix",
    "fancy",
    "meal",
    "devilish",
    "division",
    "public",
    "field",
    "stop",
    "material",
    "fluttering",
    "brass",
    "adorable",
    "camp",
    "sit",
    "tiny",
];
